name: Build Executables
on: [push]  # Triggers the workflow on every push to the repository

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, macos-latest]
        include:
          - os: windows-latest
            pyinstaller-cmd: pyinstaller --onefile --windowed --add-data "data.xlsx;." --add-data "baptisim_template_m.docx;." --add-data "baptisim_template_f.docx;." --add-data "release_situation_m.docx;." --add-data "release_situation_f.docx;." --hidden-import babel.numbers --hidden-import babel.dates main.py
            artifact-name: DocumentGenerator-Windows
          - os: macos-latest
            pyinstaller-cmd: pyinstaller --onefile --windowed --add-data "data.xlsx:." --add-data "baptisim_template_m.docx:." --add-data "baptisim_template_f.docx:." --add-data "release_situation_m.docx:." --add-data "release_situation_f.docx:." --hidden-import babel.numbers --hidden-import babel.dates main.py
            artifact-name: DocumentGenerator-Mac

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Build executable
        run: ${{ matrix.pyinstaller-cmd }}

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.artifact-name }}
          path: dist/